=== MaksSasnouskiDev/EPAM_JavaWebDevelopment/task2_xml_parser/main/resources/data/candies.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.example.com/candies"
        targetNamespace="http://www.example.com/candies"
        elementFormDefault="qualified">

    <element name="candies">
        <complexType>
            <sequence>
                <element ref="candy" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <element name="candy" type="candy_type" abstract="true"/>
    <element name="chocolate_candy" substitutionGroup="candy"/>
    <element name="caramel_candy" substitutionGroup="candy"/>

    <complexType name="candy_type">
        <sequence>
            <element name="candy_name" type="string"/>
            <element name="producer" type="string"/>
            <element name="energy" type="energy_type"/>
            <element name="expiration">
                <complexType>
                    <sequence>
                        <element name="manufacturing_date" type="date"/>
                        <element name="expiration_date" type="date"/>
                    </sequence>
                </complexType>
            </element>
            <element name="cocoaAmount" type="decimal" minOccurs="0"/>
            <element name="treacle" type="decimal" minOccurs="0"/>

        </sequence>

        <attribute name="id" use="required">
            <simpleType>
                <restriction base="id">
                    <length value="5"/>
                </restriction>
            </simpleType>
        </attribute>
        <attribute
                name="belarusian_producing" type="boolean" use="optional" default="false">
        </attribute>
    </complexType>

    <complexType name="energy_type">
        <sequence>
            <element name="total" type="decimal"/>
            <element name="protein" type="decimal"/>
            <element name="fats" type="decimal"/>
            <element name="carbs" type="decimal"/>
        </sequence>
    </complexType>

</schema>

=== MaksSasnouskiDev/EPAM_JavaWebDevelopment/task2_xml_parser/main/resources/data/candies.xml
<?xml version="1.0" encoding="UTF-8"?>
<candies xmlns="http://www.example.com/candies-instance"
         schemaLocation="http://www.example.com/candies candies.xsd">

    <chocolate_candy id="49137" >
        <candy_name>Nut Grillage</candy_name>
        <producer>Kamunarka</producer>
        <energy>
            <total>kcal="550"</total>
            <protein>8</protein>
            <fats>40</fats>
            <carbs>35</carbs>
        </energy>
        <expiration>
            <manufacturing_date>2021-11-25</manufacturing_date>
            <expiration_date>2022-05-23</expiration_date>
        </expiration>
        <cocoa>28</cocoa>
    </chocolate_candy>

    <chocolate_candy id="83924" belarusian_producing="false">
        <candy_name>Light Grillage</candy_name>
        <producer>Roshen</producer>
        <energy>
            <total>kcal="460"</total>
            <protein>12</protein>
            <fats>43</fats>
            <carbs>23</carbs>
        </energy>
        <expiration>
            <manufacturing_date>2022-02-01</manufacturing_date>
            <expiration_date>2022-08-01</expiration_date>
        </expiration>
        <cocoa>19</cocoa>
    </chocolate_candy>

    <caramel_candy id="91040">
        <candy_name>Bim-Bom</candy_name>
        <producer>Roshen</producer>
        <energy>
            <total>kcal="200"</total>
            <protein>74</protein>
            <fats>3</fats>
            <carbs>85</carbs>
        </energy>
        <expiration>
            <manufacturing_date>2022-02-01</manufacturing_date>
            <expiration_date>2022-08-01</expiration_date>
        </expiration>
        <treacle>25</treacle>
    </caramel_candy>

    <caramel_candy id="83916">
        <candy_name>Sweet Slice</candy_name>
        <producer>Roshen</producer>
        <energy>
            <total>kcal="200"</total>
            <protein>74</protein>
            <fats>3</fats>
            <carbs>85</carbs>
        </energy>
        <expiration>
            <manufacturing_date>2022-02-01</manufacturing_date>
            <expiration_date>2022-08-01</expiration_date>
        </expiration>
        <treacle>30</treacle>
    </caramel_candy>

    <waffle_candy id="73388" belarusian_producing="true">
        <candy_name>Waffle Slice</candy_name>
        <producer>Vitsba</producer>
        <energy>
            <total>kcal="430"</total>
            <protein>74</protein>
            <fats>34</fats>
            <carbs>85</carbs>
        </energy>
        <expiration>
            <manufacturing_date>2022-02-01</manufacturing_date>
            <expiration_date>2022-08-01</expiration_date>
        </expiration>
        <cocoa>25</cocoa>

    </waffle_candy>

</candies>
